package.json
source/containers/auth/Settings/views/ImportAccountView/index.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/index.ts
yarn.lock

update to latest dag4 lib
- stricter DAG address validation
- fix multiple poll timers monitoring pending txs

update to latest dag4 lib

---

source/containers/auth/Send/Send.scss
source/containers/auth/Send/Send.tsx
source/scripts/Background/controllers/AccountController.ts

feat: eth send screen mockup

---

manifest.json
source/containers/auth/Home/Home.tsx
source/scripts/Background/controllers/MessageHandler.ts
source/scripts/Provider/Script.ts
source/scripts/Provider/StargazerProvider.ts

added tabs to permissions
removed wild cards from permissions
change label from Buy DAG to Get $DAG

fix-tabs-manifest

---

source/containers/auth/Asset/Asset.tsx
source/containers/auth/Home/Home.tsx
source/hooks/usePrice.ts
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/helpers/accountMonitor.ts

fix display bitcoin value when less than .01
improve display of balances on popup by waiting for all assets to finish

refresh balances on Home and Asset views

---

source/containers/auth/Asset/AddAsset.tsx
source/containers/auth/Asset/Asset.tsx
source/containers/auth/Asset/TxsPanel.tsx
source/containers/auth/Home/AssetsPanel.tsx
source/containers/auth/helpers.tsx
source/hooks/usePrice.ts
source/pages/App/App.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/AssetsController.ts
source/scripts/Background/controllers/TransactionController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/helpers/accountMonitor.ts
source/scripts/Background/index.ts
source/state/store.ts
source/state/vault/index.ts
source/state/vault/types.ts

update ethClient and dag4 w/ network config
allow state to be rebuilt from encrypted

switch between testnet and mainnet

---

source/containers/auth/Asset/Asset.tsx
source/containers/auth/Send/Send.tsx
source/containers/auth/Settings/views/ImportAccountView/index.tsx
source/hooks/usePrice.ts
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/EthTransactionController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/index.ts

max amount send calc w/ gasPrice
make number format consistent across views

enhancement to gas speed

---

package.json
source/containers/auth/Asset/Asset.tsx
source/containers/auth/Home/AssetsPanel.tsx
source/containers/auth/Settings/views/ImportPhraseView/index.tsx
source/containers/common/Import/ImportPhrase.scss
source/containers/common/Import/ImportPhrase.tsx
source/pages/App/App.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/helpers/keystoreToKeyringHelper.ts
source/scripts/Background/migration/v2_1.ts
source/state/store.ts
source/state/vault/index.ts
source/state/vault/types.ts
yarn.lock

rename "seed phrase" to "recovery seed phrase"

migration support for v1.0

---

manifest.json
package.json
source/containers/auth/Send/Send.tsx
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/index.ts
source/scripts/Background/migration/v2_1.ts
yarn.lock

bug fix - sending DAG back to back with a fee causes white screen
improvement - reduce number of eth requests to service

dag send bug fix & eth request improvement

---

source/scenes/home/Asset/GasSettings/GasSettings.tsx
source/scenes/home/Asset/TxItem/TxItem.tsx
source/scenes/home/Asset/TxsPanel.tsx

Ticket:
https://constellationnetwork.atlassian.net/browse/SGW-9
Note: This PR includes a TypeScript fix that is required for the App to build.

V2.2 cesar comment out gas settings

---

manifest.json
package.json
source/constants/index.ts
source/containers/auth/Asset/TxsPanel.tsx
source/containers/auth/Send/Send.tsx
source/containers/auth/Settings/views/WalletsView/index.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/IAccountController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/state/assets/tokens.ts
source/state/assets/types.ts
source/utils/ledgerBridge/ledgerBridge.util.ts
yarn.lock

move AWS api calls from stargazer.network to dagexplorer.io
use estimateGasLimit to better estimate the total cost of token transfer
add Alkimi token to asset list
on change wallet, reset known balances

2.1.4 minor update

---

source/components/AssetItem/AssetItem.tsx
source/components/CircleIcon/CircleIcon.tsx
source/scenes/home/Send/Confirm.tsx
source/scenes/home/Send/Send.tsx
source/scripts/Background/controllers/IAccountController.ts
source/scripts/Provider/EthereumProvider.ts

estimate token transfers for providing more accurate transfer costs

fix icon path for absolute urls

---

source/scenes/home/Home/Home.scss
views/app.html

This fixes the following two tickets:
https://constellationnetwork.atlassian.net/browse/SGW-12
https://constellationnetwork.atlassian.net/browse/SGW-13

Changed: Moved the your assets section up to reveal the ADS token

---

source/scripts/Background/controllers/MessageHandler.ts
source/scripts/Background/controllers/index.ts
source/scripts/ContentScript/inject.ts
source/scripts/Provider/EthereumProvider.ts
source/scripts/Provider/StargazerProvider.ts

Adds handling for ETH messages on window.stargazer to support eth_chainId. Maps to the correct provider based on asset in MessageHandler.

V3.1.0 alex get eth chain

---

source/navigation/headers/config.ts
source/web/package.json
source/web/webpack.config.js
yarn.lock

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-63

Sgw 63 extension resolve build issues

---

source/scenes/common/Import/ImportPhrase.tsx

Remove the span element containing a message that users found to be confusing.

Removed: confusing seed import message

---

source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/migration/update_token_list.ts
source/state/assets/tokens.ts

- Updates the DODI asset ID in initialState. 
- Adds a check on each initial load of the extension to see if user's asset state matches the asset initialState in the codebase and updates it if it doesn't match. The asset list isn't ever updated dynamically so this strategy should make upgrades more straightforward.

Update asset list any time it diverges from initialState assets

---

source/navigation/stacks/Home.tsx
source/navigation/stacks/Settings.tsx
source/scenes/common/Import/CreatePass/CreatePass.container.tsx
source/scenes/common/Import/ImportPhrase/ImportPhrase.container.tsx
source/scenes/common/Login/Login.container.tsx
source/scenes/home/Asset/AddAsset/AddAsset.container.tsx
source/scenes/home/Asset/Asset/Asset.container.tsx
source/scenes/home/Asset/TxItem/TxItem.container.tsx
source/scenes/settings/About/About.native.tsx
source/scenes/settings/ImportAccount/ImportAccount.container.tsx
source/scenes/settings/ImportPhrase/ImportPhrase.container.tsx
source/scenes/settings/Main/Main.container.tsx
source/scenes/settings/ManageWallet/ManageWallet.container.tsx
source/scenes/settings/ModifyContact/ModifyContact.container.tsx
source/scenes/settings/Networks/Networks.container.tsx
source/scenes/settings/NewAccount/NewAccount.container.tsx
source/scenes/settings/Phrase/Phrase.container.tsx
source/scenes/settings/PrivateKey/PrivateKey.container.tsx
source/scenes/settings/RemoveWallet/RemoveWallet.container.tsx
source/scenes/settings/Wallets/Wallets.container.tsx
source/scenes/unauth/CreatePass/CreatePass.container.tsx
source/scenes/unauth/Phrase/ConfirmPhrase/ConfirmPhrase.container.tsx
source/scenes/unauth/Phrase/CreatePhrase/CreatePhrase.container.tsx
source/utils/controllersUtils.native.ts
source/utils/controllersUtils.ts

Had to revert a previous revert which merged changes involving how we import walletController in the app.
The following scenes were updated to use walletController new import style
- settings
- asset scenes
- unauth scenes
- /stacks/home 
- stacks/Settings

Development/trini/sgw 121/walletcontroller update

---

source/scenes/settings/Main/Main.native.tsx
source/scenes/settings/Main/types.ts

https://constellationnetwork.atlassian.net/browse/SGW-126

remove connected-sites link on main settings

---

source/components/TextV3/styles.ts
source/scenes/common/Import/CreatePass/CreatePass.native.tsx
source/scenes/common/Import/CreatePass/styles.ts
source/scenes/common/Login/Login.native.tsx
source/scenes/settings/AddWallet/styles.ts
source/scenes/settings/ImportAccount/ImportAccount.native.tsx
source/scenes/settings/ImportAccount/ImportAccount.tsx
source/scenes/settings/ManageWallet/styles.ts
source/scenes/settings/NewAccount/NewAccount.native.tsx
source/scenes/unauth/CreatePass/CreatePass.native.tsx
source/scenes/unauth/CreatePass/styles.ts
source/scenes/unauth/Phrase/ConfirmPhrase/ConfirmPhrase.native.tsx
source/scenes/unauth/Phrase/ConfirmPhrase/styles.tsx
source/scenes/unauth/Start/Start.native.tsx

https://constellationnetwork.atlassian.net/browse/SGW-127
https://constellationnetwork.atlassian.net/browse/SGW-123
https://constellationnetwork.atlassian.net/browse/SGW-122
https://constellationnetwork.atlassian.net/browse/SGW-124
https://constellationnetwork.atlassian.net/browse/SGW-128
Updated various style bugs:

Development/trini/sgw 127/add wallet styling

---

source/scenes/home/Home/Home.native.tsx
source/scenes/home/Home/styles.ts

Fix scroll issue in home view.
Set container wrapper to flexGrow:1, and remove any height styles with percentages.
Adding fixed height: 200 for the balance.

Development/trini/sgw 125/scroll issue

---

source/components/PurpleSlider/PurpleSlider.native.tsx
source/components/PurpleSlider/styles.ts
source/scenes/home/Asset/TxItem/TxItem.container.tsx
source/scenes/home/SendAsset/Send/Send.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-146

Fixed: Send screen gas slider

---

source/components/AssetItem/styles.ts
source/components/Card/styles.ts
source/components/Container/styles.ts
source/components/FileSelect/styles.ts
source/components/Link/styles.ts
source/components/PurpleSlider/PurpleSlider.native.tsx
source/components/PurpleSlider/styles.ts
source/components/Select/styles.ts
source/components/ToastAlert/styles.ts
source/components/Tooltip/styles.ts
source/scenes/home/Asset/Asset/styles.ts
source/scenes/home/Asset/AssetHeader/styles.ts
source/scenes/home/Home/AssetsPanel/AssetsPanel.native.tsx
source/scenes/home/Home/AssetsPanel/styles.ts
source/scenes/settings/ContactInfo/ContactInfo.container.tsx
source/scenes/settings/ContactInfo/ContactInfo.native.tsx
source/scenes/settings/ModifyContact/ModifyContact.native.tsx
source/scenes/settings/ModifyContact/styles.ts
source/scenes/settings/Networks/styles.ts
source/scenes/settings/Wallets/styles.ts
source/scenes/unauth/CreatePass/styles.ts
source/scenes/unauth/Start/styles.ts

- Fixing up some minor styling errors, cleaning up invalid style props
- Fix copy clipboard in ContactInfo
- Fix modifyContact scene not working
- Fix margin bottom in Asset Panel
- Fix verified icon in Add Contact form to be more centered

Development/trini/sgw 154/fix misc errors

---

source/scenes/home/Home/AssetsPanel/AssetsPanel.container.tsx
source/scenes/home/Home/AssetsPanel/AssetsPanel.native.tsx
source/scenes/home/Home/AssetsPanel/AssetsPanel.tsx
source/scenes/home/Home/AssetsPanel/types.ts

Fixed broken nft link on mobile by moving the `handleSelectNFT` to respective native and web components.

fix nft link

---

source/components/ButtonV3/styles.ts
source/scenes/home/SendAsset/Confirm/Confirm.native.tsx
source/scenes/home/SendAsset/Send/Send.native.tsx
source/scenes/home/SendAsset/Send/styles.ts
source/scenes/settings/ContactInfo/ContactInfo.native.tsx
source/scenes/settings/ContactInfo/styles.ts
source/scenes/settings/ImportAccount/ImportAccount.native.tsx
source/scenes/settings/ImportAccount/styles.ts
source/scenes/settings/ImportPhrase/ImportPhrase.native.tsx
source/scenes/settings/ImportPhrase/styles.ts
source/scenes/settings/ManageWallet/ManageWallet.native.tsx
source/scenes/settings/ManageWallet/styles.ts
source/scenes/settings/ModifyContact/ModifyContact.native.tsx
source/scenes/settings/ModifyContact/styles.ts
source/scenes/settings/NewAccount/NewAccount.native.tsx
source/scenes/settings/NewAccount/styles.ts
source/scenes/settings/PrivateKey/PrivateKey.native.tsx
source/scenes/settings/RemoveWallet/RemoveWallet.native.tsx
source/scenes/settings/RemoveWallet/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-157

Cesar sgw 157 send screen buttons overlap and are wrong color

---

source/scenes/settings/ImportAccount/ImportAccount.native.tsx
source/scenes/settings/ManageWallet/ManageWallet.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-158

Cesar sgw 158 multi chain wallets show export private key instead of recovery phrase

---

source/scenes/settings/About/About.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-160

Removed: Mentions of the chrome extension

---

source/scenes/home/Asset/Asset/styles.ts
source/scenes/home/Asset/TxsPanel/TxsPanel.native.tsx
source/scenes/home/Asset/TxsPanel/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-161

Fixed: Issue where transaction history background would be cut off

---

source/components/AssetItem/AssetItem.native.tsx
source/components/AssetItem/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-162

Fixed: Alignment issue, and price delta incorrect color

---

source/scenes/home/SendAsset/Send/Send.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-163

Changed: Amount and trasnsaction fee keyboards to decimal pads

---

source/scenes/home/SendAsset/Send/Send.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-165

Added: KeyboardAvoidingView to the send screen

---

source/scenes/settings/ModifyContact/ModifyContact.container.tsx
source/scenes/settings/ModifyContact/ModifyContact.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-169

Fixed: Modifiy Contact now populates the address field

---

source/navigation/stacks/Settings.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-174

Removed: Animation when clicking on the hamburger menu

---

source/navigation/stacks/Settings.tsx

Reverts StardustCollective/stargazer-wallet-ext#241

Revert "Removed: Animation when clicking on the hamburger menu"

---

source/native/App.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-180

Changed: Status Bar style to light-cotent

---

source/components/ButtonV3/ButtonV3.native.tsx
source/scenes/common/Login/Login.container.tsx
source/scenes/common/Login/Login.native.tsx
source/scenes/common/Login/types.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-172

Cesar sgw 172 sign in lag on unlock screen

---

source/scenes/home/Asset/Asset/Asset.native.tsx
source/scenes/home/Asset/Asset/styles.ts
source/scenes/home/Asset/TxsPanel/TxsPanel.native.tsx
source/scenes/home/Asset/TxsPanel/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-181

Changed: The asset scene will now scroll as a whole

---

source/components/TextInput/TextInput.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-176

Cesar sgw 176 update text inputs to inlcude done button to allow exit

---

source/scenes/settings/ContactInfo/ContactInfo.native.tsx
source/scenes/settings/ContactInfo/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-167?atlOrigin=eyJpIjoiNjdmZDc3YzFhNzIzNDYzMGFmNGRkYzc0YzA2ZDhiMDAiLCJwIjoiaiJ9

Cesar sgw 167 mobile qr code in contact info is not centered

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Confirm/Confirm.native.tsx
source/scenes/home/SendAsset/Confirm/styles.ts
source/scenes/settings/ContactInfo/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-170
Note: Only 3 screens had misaligned buttons.

Cesar sgw 170 button should always align to the bottom of the screen for consistency

---

patches/@stardust-collective+dag4-keyring+0.0.13.patch
source/scripts/Background/controllers/WalletController.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-187

Fixed: Issue where login would fail intermittently do to a race condition in the login sequence

---

source/native/package.json
source/navigation/headers/asset/asset.native.tsx
source/navigation/headers/asset/styles.ts
source/scenes/common/Import/CreatePass/CreatePass.native.tsx
source/scenes/common/Import/CreatePass/styles.ts
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Confirm/styles.ts
source/scenes/home/SendAsset/Send/Send.native.tsx
source/scenes/home/SendAsset/Send/styles.ts
source/scenes/settings/About/About.container.tsx
source/scenes/settings/Main/Main.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-193

Fixed: iPod style issues

---

source/scenes/home/Asset/TxItem/TxItem.native.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/types.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-192

Cesar sgw 192 pending send transaction created for erc 20 contract address

---

source/scenes/settings/About/About.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-195

Updated: Privacy policy link in the settings about scene

---

source/scenes/external/SignatureRequest/index.tsx
source/scripts/Background/controllers/MessageHandler/requests.ts
source/scripts/ContentScript/index.ts
source/scripts/ContentScript/inject/stargazerProvider.txt.ts
source/scripts/Provider/EthereumProvider.ts

[LE-236] (https://constellationnetwork.atlassian.net/browse/LE-236)
Favoring compatibility with MetaMask's `personal_sign` method.
+ Removed schema verification for ETH signing.
+ Removed metadata title when there is no metadata.
[LE-236]: https://constellationnetwork.atlassian.net/browse/LE-236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removed ETH signature schema verification

---

source/scenes/external/SignatureRequest/index.tsx
source/scripts/Background/controllers/MessageHandler/requests.ts
source/scripts/ContentScript/index.ts
source/scripts/ContentScript/inject/stargazerProvider.txt.ts
source/scripts/Provider/EthereumProvider.ts

* removed schema verification
* Update source/scenes/external/SignatureRequest/index.tsx
Co-authored-by: Alex Brandes <asbrandes@gmail.com>
* multiple changes
+ Require the request address to be the same as the active wallet.
+ Support for hex messages signing (eth).
+ Extend RPCError from Error.
+ Add new version property to the provider, the Stargazer version.
Co-authored-by: Alex Brandes <asbrandes@gmail.com>

Removed ETH signature schema verification (#229)

---

source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/home/SendAsset/Send/Send.native.tsx
source/utils/sendUtil.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-191
If a period is not present, the user is able to enter only one:
The user is unable to enter a second period:

Juan sgw 191 two period characters crash

---

source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/settings/ModifyContact/ModifyContact.container.tsx
source/utils/addressUtil.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-194

Juan sgw 194 scanning QR code ethereum prefix

---

source/native/android/app/build.gradle

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-203

Juan sgw 203 android platform setup

---

source/state/assets/index.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-220

Fixed: GeoJam Price ID

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Confirm/Confirm.native.tsx
source/scenes/home/SendAsset/Confirm/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-211

Juan sgw 211 styles updated in confirm transaction scene

---

source/scenes/settings/ImportAccount/ImportAccount.native.tsx
source/scenes/settings/ImportAccount/styles.ts
source/scenes/settings/ModifyContact/styles.ts
source/scenes/settings/NewAccount/styles.ts
source/scenes/settings/RemoveWallet/RemoveWallet.native.tsx
source/scenes/settings/RemoveWallet/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-210

Juan sgw 210 buttons spacing for android

---

source/scenes/common/Login/styles.native.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-208

Juan sgw 208 welcome title style updated for Android

---

source/native/App.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-213

Juan sgw 213 status bar color updated for android platform

---

source/scenes/home/Contacts/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-212

Juan sgw 212 contracts modal from send scene

---

source/scenes/settings/Contacts/Contacts.native.tsx
source/scenes/settings/Contacts/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-228

Juan sgw 228 add contact text style updated

---

source/scenes/settings/Main/Main.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-225

Juan sgw 225 settings scene font color

---

source/native/android/app/build.gradle

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-206

Juan sgw 206 android jscFlavor update to support different locales

---

source/scenes/home/SendAsset/Send/Send.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-205

Juan sgw 205 two period android crash

---

source/native/android/app/build.gradle
source/native/android/app/src/main/AndroidManifest.xml

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-106
**Additional comment:** I also updated the `versionCode` because I've been doing some testing with Internal Testing releases.

Juan sgw 230 android screen orientation and version format

---

source/scenes/home/SendAsset/Send/Send.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-227
User gets error when entering comma character:
User is able to enter comma character:

Juan sgw 227 comma char replaced with dot char

---

source/native/android/app/build.gradle
source/native/android/app/src/main/AndroidManifest.xml

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-243

Juan sgw 243 support only phones

---

source/scenes/settings/ContactInfo/ContactInfo.native.tsx
source/scenes/settings/ContactInfo/ContactInfo.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-246

Juan sgw 246 app crash on contact delete

---

source/scenes/home/SendAsset/Send/Send.native.tsx
source/scenes/home/SendAsset/Send/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-248

Juan sgw 248 gas settings with 3 digits issue

---

source/scenes/settings/Wallets/Wallets.native.tsx
source/scenes/settings/Wallets/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-250
Android:
iOS:
Android:
iOS:

Juan sgw 250 info icon in wallets scene

---

source/components/AssetItem/AssetItem.native.tsx
source/components/AssetItem/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-249

Juan sgw 249 NFT image style and quantity

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-244

Juan sgw 244 background dispatch for confirmEvent

---

source/native/android/app/build.gradle

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-268

Juan sgw 268 hermes enabled

---

source/scenes/settings/RemoveWallet/RemoveWallet.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-260

Juan sgw 260 remove wallet crash

---

source/scenes/settings/Wallets/Wallets.native.tsx
source/scenes/settings/Wallets/Wallets.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-262

Juan sgw 262 active wallet crash

---

source/components/Container/Container.scss
source/components/Container/Container.tsx
source/scenes/home/SendAsset/Send/Send.scss
source/scenes/settings/ImportAccount/ImportAccount.scss
source/scenes/settings/ImportPhrase/ImportPhrase.scss
source/scenes/settings/NewAccount/NewAccount.scss
source/scenes/settings/RemoveWallet/RemoveWallet.scss

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-255
Ticket: https://constellationnetwork.atlassian.net/browse/SGW-256

Juan sgw 255 extension style issues

---

source/scripts/Background/controllers/EthTransactionController.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-261

Juan sgw 261 window.controller crash on mobile

---

source/native/android/app/src/main/java/com/stargazer/MainActivity.java

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-259

Juan sgw 259 android react-native-screens crash

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Confirm/Confirm.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-270

Juan sgw 270 only web import in container file

---

source/scenes/unauth/Phrase/ConfirmPhrase/ConfirmPhrase.container.tsx
source/scenes/unauth/Phrase/CreatePhrase/CreatePhrase.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-236

Juan sgw 236 getWalletController inside component

---

patches/@stardust-collective+dag4-ledger+0.0.12.patch
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scripts/Background/controllers/MessageHandler/requests.ts
source/scripts/Background/controllers/index.ts
source/web/package.json
source/web/pages/Ledger/Ledger.tsx
source/web/pages/Ledger/views/messageSigning/index.ts
source/web/pages/Ledger/views/messageSigning/messageSigning.view.tsx
source/web/pages/Ledger/views/messageSigning/styles.module.scss
source/web/utils/ledgerBridge/ledgerBridge.util.ts

Tickets:
https://constellationnetwork.atlassian.net/browse/SGW-257
https://constellationnetwork.atlassian.net/browse/SGW-287

Cesar sgw stargazer implement blind signing for ledger

---

source/native/App.tsx
source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/migration/update_token_list.ts
source/scripts/Background/migration/v2_1.ts
source/scripts/Background/migration/v3_1_1.ts
source/scripts/Background/migration/v3_3.ts
source/scripts/Background/migration/v3_4_2.ts
source/state/providers/index.ts
source/state/store.ts
source/utils/browser.native.ts
source/utils/browser.ts
source/utils/envUtil.native.ts
source/utils/envUtil.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-234

Juan sgw 234 migration mobile and web

---

source/web/manifest.json

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-302

Juan sgw 302 content security policy updated

---

source/scenes/home/BuyAsset/BuyAsset.native.tsx
source/scenes/home/BuyAsset/BuyAsset.tsx
source/scenes/home/BuyAsset/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-291

Juan sgw 291 confirm button style update

---

source/scenes/settings/ContactInfo/ContactInfo.container.tsx
source/scenes/settings/ModifyContact/ModifyContact.container.tsx
source/utils/controllersUtils.native.ts
source/utils/controllersUtils.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-258

Juan sgw 258 add or remove contact logic updated

---

source/scenes/home/BuyAsset/BuyAsset.container.tsx
source/scenes/home/BuyList/BuyList.container.tsx
source/scenes/settings/Wallets/Wallets.native.tsx
source/scenes/settings/Wallets/styles.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-303

Juan sgw 303 app crash on private key import

---

source/scripts/Background/controllers/WalletController.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-253

Juan sgw 253 logout extension crash

---

source/scripts/Background/controllers/index.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-308

Juan sgw 308 popup not showing up

---

source/native/index.js
source/native/package.json
source/scripts/Background/controllers/index.ts
yarn.lock

[Soft Nodes - Stargazer Signature Bug](https://constellationlabs.slack.com/archives/C02CWP3BPKK/p1654259173320779)
+ Used the `URLSearchParams` API instead.
+ Added new polyfill for react-native.

Fixed createPopup(); params encoding bug

---

source/constants/index.ts
source/scenes/settings/Networks/Networks.container.tsx
source/scripts/Background/controllers/EthChainController/types.ts
source/scripts/Background/controllers/EthChainController/utils.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-323

Juan sgw 323 rinkeby testnet

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-343?atlOrigin=eyJpIjoiN2FkYTgxZmQ5MTZlNGE2YjkwMmM2NjJhNGJlM2MwNDIiLCJwIjoiaiJ9

Fixed: Issue where a white screen would be shown when sending an asset

---

source/constants/index.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-334

Changed: DAG Config URLs

---

package.json
source/components/Container/Container.tsx
source/hooks/index.ts
source/scenes/home/Asset/GasSettings/GasSettings.tsx
source/web/pages/Bitfi/views/accounts/accounts.view.tsx
source/web/pages/Ledger/views/accounts/accounts.view.tsx
yarn.lock

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-346

Fixed: Typescript errors

---

source/utils/ethUtil.ts

PR: https://constellationnetwork.atlassian.net/browse/SGW-347

Juan SGW gas estimation issue

---

source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/home/SendAsset/Send/Send.native.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-247

Juan sgw 247 amount validation in send screen

---

source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/utils/dagUtils.ts

[SGW-367](https://constellationnetwork.atlassian.net/browse/SGW-367)
+ Fixes references of dag4.js `getBalance()` for undefined returns.

Fixed asset screen NaN display

---

patches/@stardust-collective+dag4-keystore+1.0.11.patch
source/scripts/Provider/StargazerProvider.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-381

Cesar sgw 381 web extension patch dag4 libraries with new personal sign method

---

source/scripts/Background/controllers/DAppController.ts
source/scripts/Background/controllers/MasterController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/dappRegistry/dappProvider.ts
source/scripts/Background/dappRegistry/dappRegistry.ts
source/scripts/Background/dappRegistry/requests/event.ts
source/scripts/Background/index.ts
source/state/dapp/index.ts
source/state/dapp/types.ts
source/utils/controllersUtils.ts

+ Fixed `accountsChanged` and `disconnect` RPC events.
+ Added `chainChanged` RPC event.
+ Moved events and listener's logic to `DappRegistry` and `DappProvider` (from `state` and `DAppController`).
+ Code Linting.

Fixed RPC events system

---

source/web/pages/App/index.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-385

Fixed: Issue where importing an account by JSON file would fail

---

source/scenes/settings/RemoveWallet/RemoveWallet.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-394

Fixed: Issue where users main account seed phrase would be displayed

---

source/constants/index.ts
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/home/SendAsset/Send/Send.native.tsx
source/scenes/home/SendAsset/Send/Send.tsx
source/scenes/home/SendAsset/Send/types.ts
source/scripts/Background/controllers/AssetsController.ts
source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/EVMChainController/utils.ts
source/scripts/Background/controllers/NetworkController.ts
source/state/erc20assets/api.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-349

Juan SGW 349 bug fixes

---

source/scripts/Background/controllers/AssetsController.ts
source/state/assets/index.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-424
This PR fixes the token balance issue. (USDC)

Juan SGW 424 ERC-20 tokens decimals

---

source/components/AssetItem/AssetItem.native.tsx
source/components/AssetItem/AssetItem.tsx
source/components/QRCodeModal/QRCodeModal.tsx
source/scenes/home/Asset/AddCustomAsset/AddCustomAsset.container.tsx
source/scenes/home/Asset/Asset/Asset.native.tsx
source/scenes/home/Asset/AssetHeader/AssetHeader.container.tsx
source/scenes/home/Asset/AssetList/AssetList.native.tsx
source/scenes/home/Asset/AssetList/AssetList.tsx
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/settings/Networks/Networks.container.tsx
source/scenes/settings/Networks/Networks.native.tsx
source/scenes/settings/Networks/Networks.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/EVMChainController/EVMChainController.ts
source/scripts/Background/controllers/EVMChainController/utils.ts
source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/controllers/NetworkController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/scripts/Background/migration/v3_8_2.ts
source/selectors/walletsSelectors.ts
source/state/assets/index.ts
source/state/erc20assets/index.ts
source/state/erc20assets/utils.ts
source/state/vault/index.ts
source/state/vault/types.ts

This PR adds support to Avalanche network.

Juan SGW 349 adds avalanche network

---

source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/home/SendAsset/Send/types.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-428
This PR fixes the following error:

Juan SGW 428 RPC provider issues in stargazer demos

---

package.json
source/components/AssetItem/AssetItem.native.tsx
source/components/AssetItem/AssetItem.tsx
source/components/QRCodeModal/QRCodeModal.tsx
source/scenes/home/Asset/AddCustomAsset/AddCustomAsset.container.tsx
source/scenes/home/Asset/Asset/Asset.native.tsx
source/scenes/home/Asset/AssetHeader/AssetHeader.container.tsx
source/scenes/home/Asset/AssetList/AssetList.native.tsx
source/scenes/home/Asset/AssetList/AssetList.tsx
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/settings/Networks/Networks.container.tsx
source/scenes/settings/Networks/Networks.native.tsx
source/scenes/settings/Networks/Networks.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/EVMChainController/utils.ts
source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/controllers/NetworkController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/scripts/Background/migration/v2_1.ts
source/scripts/Background/migration/v3_8_3.ts
source/selectors/walletsSelectors.ts
source/state/assets/index.ts
source/state/erc20assets/index.ts
source/state/erc20assets/utils.ts
source/state/vault/index.ts
source/state/vault/types.ts

This PR adds support to BSC network

Juan SGW 349 adds bsc network

---

source/constants/index.ts
source/scenes/home/Asset/TxItem/TxItem.native.tsx
source/scenes/home/Asset/TxItem/TxItem.tsx
source/scenes/home/Asset/TxsPanel/TxsPanel.container.tsx
source/scenes/home/Home/Home.native.tsx
source/scenes/home/Home/Home.scss
source/scenes/home/Home/Home.tsx
source/scenes/home/Home/styles.ts
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/home/helpers.tsx
source/scenes/settings/Networks/Networks.container.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/EVMChainController/utils.ts
source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/index.ts
source/scripts/Background/migration/v3_9_1.ts
source/scripts/Provider/StargazerProvider.ts
source/state/vault/index.ts
source/web/pages/Bitfi/Bitfi.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-436

Juan SGW 436 removes mainnet 1.0

---

source/web/utils/bitfiBridge/index.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-438

Fixed: Issue where sending DAG with a bitfi device would fail on Mainnet 2.0

---

source/scenes/swap/SwapTokens/SwapTokens.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-448

Fixed: Issue where the Swap From balance would infinitly loop

---

source/scenes/swap/SwapTokens/SwapTokens.container.tsx
source/scenes/swap/TokenList/TokenList.container.tsx
source/scenes/swap/TokenList/TokenList.native.tsx
source/scenes/swap/TokenList/TokenList.tsx
source/scenes/swap/TokenList/types.ts
source/scripts/Background/controllers/SwapController.ts
source/state/swap/api.ts
source/state/swap/index.ts
source/state/swap/types.ts

- Fixed issue where on first open of the Swap Token view the balance would be shown as zero
- Fixed issue where the swap from balance would not update in the Swap Tokens screen after performing a swap.
Tickets:
https://constellationnetwork.atlassian.net/browse/SGW-458
https://constellationnetwork.atlassian.net/browse/SGW-454

SGW-458 and SGW-454

---

source/scenes/swap/SwapTokens/SwapTokens.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-452

Fixes: Comma input issue for international keyboards

---

source/scenes/home/Asset/Asset/Asset.container.tsx
source/scripts/Background/controllers/WalletController.ts
source/scripts/Provider/StargazerProvider.ts
source/scripts/types.ts
source/web/pages/Ledger/Ledger.tsx

Tickets: 
https://constellationnetwork.atlassian.net/browse/SGW-450
https://constellationnetwork.atlassian.net/browse/SGW-451

Cesar sgw 451 incorrect bitpath index is being passed to the ledger native code

---

source/scenes/home/Asset/Asset/Asset.container.tsx
source/scripts/Background/controllers/WalletController.ts
source/scripts/Provider/StargazerProvider.ts
source/scripts/types.ts
source/web/pages/Ledger/Ledger.tsx

Reverts StardustCollective/stargazer-wallet-ext#377

Revert "Cesar sgw 451 incorrect bitpath index is being passed to the ledger native code"

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-493

Fixed: Issue where bitfi transaction would fail to open the sign page

---

source/navigation/headers/asset/asset.native.tsx
source/navigation/headers/asset/asset.tsx
source/scenes/home/Asset/TxsPanel/TxsPanel.container.tsx
source/scenes/home/helpers.tsx

Tickets:
https://constellationnetwork.atlassian.net/browse/SGW-496
https://constellationnetwork.atlassian.net/browse/SGW-497
https://constellationnetwork.atlassian.net/browse/SGW-498

Juan SGW 496 unhandled errors (undefined is not an object)

---

source/scenes/settings/Wallets/Wallets.container.tsx
source/selectors/walletsSelectors.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-499

Juan SGW 499 cannot convert undefined value to object in hardware wallets

---

source/scripts/Provider/EthereumProvider.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-504

Juan SGW 504 reject sign request if chain id does not match

---

source/scenes/swap/SwapTokens/SwapTokens.container.tsx
source/scripts/Background/controllers/SwapController.ts
source/state/swap/api.ts
source/state/swap/types.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-506

Cesar sgw 506 exolix swap used incorrect network polygon vs erc20 user fund lost

---

source/scenes/home/SendAsset/Send/Send.container.tsx

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-507

Juan SGW 507 eth transfer displays wrong amount

---

source/constants/index.ts
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scripts/Background/controllers/WalletController.ts
source/scripts/Provider/StargazerProvider.ts
source/scripts/common/availableChainMethods.ts
source/scripts/common/availableMethods.ts

Ticket: https://constellationnetwork.atlassian.net/browse/SGW-503

Juan SGW 503 add dag_sendTransaction method

---

source/assets/styles/_variables.native.ts
source/assets/styles/_variables.scss
source/components/ButtonV3/ButtonV3.tsx
source/components/TextV3/TextV3.scss
source/components/TextV3/TextV3.tsx
source/components/TextV3/styles.ts
source/scenes/common/Login/Login.native.tsx
source/scenes/common/Login/Login.tsx
source/scenes/common/Login/styles.native.ts
source/scenes/common/Login/styles.scss
source/scenes/unauth/Start/Start.native.tsx
source/scenes/unauth/Start/Start.scss
source/scenes/unauth/Start/Start.tsx
source/scenes/unauth/Start/styles.ts

Ticket: [SGW-511](https://constellationnetwork.atlassian.net/browse/SGW-511)
[SGW-511]: https://constellationnetwork.atlassian.net/browse/SGW-511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 511 login & start screens UI

---

source/scenes/external/TypedSignatureRequest/index.module.scss
source/scenes/external/TypedSignatureRequest/index.tsx
source/scenes/external/TypedSignatureRequest/types.ts
source/scripts/Provider/EthereumProvider.ts

Ticket: [SGW-510](https://constellationnetwork.atlassian.net/browse/SGW-510)
Domain section is now displayed in the signature request:
[SGW-510]: https://constellationnetwork.atlassian.net/browse/SGW-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 510 ETH typed data domain section

---

source/assets/images/svg/copy.svg
source/components/ButtonV3/ButtonV3.scss
source/components/ButtonV3/ButtonV3.tsx
source/components/Container/Container.scss
source/components/TextV3/TextV3.scss
source/scenes/external/Layouts/CardLayoutV2/index.module.scss
source/scenes/external/Layouts/CardLayoutV2/index.tsx
source/scenes/external/TypedSignatureRequest/index.module.scss
source/scenes/external/TypedSignatureRequest/index.tsx
source/scenes/home/Contacts/Contacts.scss
source/scenes/home/Contacts/Contacts.tsx
source/scenes/home/SendAsset/Send/Send.scss
source/scripts/Provider/EthereumProvider.ts
source/web/pages/External/App.tsx
views/external.html

Ticket: [SGW-510](https://constellationnetwork.atlassian.net/browse/SGW-510)
Screenshots:
[SGW-510]: https://constellationnetwork.atlassian.net/browse/SGW-510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 510 signature request UI update

---

source/scenes/settings/ImportAccount/ImportAccount.container.tsx
source/scripts/Background/controllers/WalletController.ts

Ticket: [SGW-581](https://constellationnetwork.atlassian.net/browse/SGW-581)
[SGW-581]: https://constellationnetwork.atlassian.net/browse/SGW-581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 581 import DAG wallet via private key not updating

---

source/scenes/settings/Wallets/Wallets.container.tsx

Ticket: [SGW-224](https://constellationnetwork.atlassian.net/browse/SGW-224)
[SGW-224]: https://constellationnetwork.atlassian.net/browse/SGW-224?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 224 navigate to home screen when selecting a wallet

---

source/scenes/home/SendAsset/Confirm/Confirm.native.tsx
source/scripts/Background/controllers/AccountController.ts

Ticket: [SGW-440](https://constellationnetwork.atlassian.net/browse/SGW-440)
[SGW-440]: https://constellationnetwork.atlassian.net/browse/SGW-440?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 440 DAG pending transactions fix

---

source/scenes/home/Home/Home.container.tsx
source/scenes/home/helpers.tsx
source/scenes/settings/Wallets/Wallets.native.tsx
source/scenes/settings/Wallets/Wallets.tsx

Ticket: [SGW-251](https://constellationnetwork.atlassian.net/browse/SGW-251)
[SGW-251]: https://constellationnetwork.atlassian.net/browse/SGW-251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 251 wallet name too long

---

source/components/AssetItem/AssetItem.native.tsx
source/components/AssetItem/AssetItem.tsx
source/scenes/home/helpers.tsx
source/scripts/Background/controllers/EVMChainController/AccountTracker.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts

Ticket: [SGW-543](https://constellationnetwork.atlassian.net/browse/SGW-543)
[SGW-543]: https://constellationnetwork.atlassian.net/browse/SGW-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 543 display dash when balance is not available

---

source/components/ButtonV3/ButtonV3.tsx
source/components/PurpleSlider/PurpleSlider.tsx
source/scenes/home/Asset/Asset/Asset.container.tsx
source/scenes/home/Asset/GasSettings/GasSettings.container.tsx
source/scenes/home/Asset/GasSettings/GasSettings.native.tsx
source/scenes/home/Asset/GasSettings/GasSettings.scss
source/scenes/home/Asset/GasSettings/GasSettings.tsx
source/scenes/home/Asset/GasSettings/constants.ts
source/scenes/home/Asset/GasSettings/styles.ts
source/scenes/home/Asset/GasSettings/types.ts
source/scenes/home/Asset/TxItem/TxItem.container.tsx
source/scenes/home/Asset/TxItem/TxItem.native.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/WalletController.ts

Ticket: [SGW-529](https://constellationnetwork.atlassian.net/browse/SGW-529)
[SGW-529]: https://constellationnetwork.atlassian.net/browse/SGW-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 529 cancel pending transaction

---

source/scenes/unauth/Phrase/ConfirmPhrase/ConfirmPhrase.container.tsx
source/scenes/unauth/Phrase/ConfirmPhrase/ConfirmPhrase.native.tsx
source/scenes/unauth/Phrase/ConfirmPhrase/ConfirmPhrase.tsx
source/scenes/unauth/Phrase/ConfirmPhrase/types.ts

Ticket: [SGW-590](https://constellationnetwork.atlassian.net/browse/SGW-590)
[SGW-590]: https://constellationnetwork.atlassian.net/browse/SGW-590?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 590 double-clicking wallet creation

---

source/components/Card/Card.native.tsx
source/scenes/settings/Main/Main.native.tsx
source/scenes/settings/Main/styles.ts
source/scenes/settings/Main/types.ts

Ticket: [SGW-539](https://constellationnetwork.atlassian.net/browse/SGW-539)
[SGW-539]: https://constellationnetwork.atlassian.net/browse/SGW-539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 539 grey out security section

---

source/scenes/swap/SwapTokens/constants.ts
source/selectors/swapSelectors.ts
source/state/swap/api.ts
source/state/swap/index.ts
source/state/swap/types.ts

Ticket: [SGW-636](https://constellationnetwork.atlassian.net/browse/SGW-636)
[SGW-636]: https://constellationnetwork.atlassian.net/browse/SGW-636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 636 swap tokens list

---

source/scenes/home/Home/Home.container.tsx
source/scenes/home/Home/Home.tsx
source/scenes/home/Home/WalletsModal/WalletsModal.scss
source/scenes/home/Home/WalletsModal/WalletsModal.tsx
source/scenes/home/Home/WalletsModal/types.ts
source/scenes/home/Home/types.tsx

Ticket:  [SGW-659](https://constellationnetwork.atlassian.net/browse/SGW-659)
[SGW-659]: https://constellationnetwork.atlassian.net/browse/SGW-659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 659 added hardware wallets in bottom modal

---

source/scripts/Background/controllers/EVMChainController/etherscanApi.ts
source/utils/objects.ts

Ticket: [SGW-641](https://constellationnetwork.atlassian.net/browse/SGW-641)
[SGW-641]: https://constellationnetwork.atlassian.net/browse/SGW-641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 641 adds internal transactions

---

source/scenes/home/SendAsset/Send/Send.container.tsx

Ticket: [SGW-680](https://constellationnetwork.atlassian.net/browse/SGW-680)
[SGW-680]: https://constellationnetwork.atlassian.net/browse/SGW-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 680 gas slider not showing

---

source/constants/events.ts
source/scenes/home/Home/Home.native.tsx
source/scenes/home/Home/Home.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/nfts/Collections/Collections.container.tsx
source/scenes/nfts/NFTSend/NFTSend.container.tsx
source/scenes/nfts/NFTSend/NFTSend.native.tsx
source/scenes/nfts/NFTSend/NFTSend.tsx
source/scenes/nfts/NFTSendConfirm/NFTSendConfirm.container.tsx
source/utils/EventEmitter.ts

Ticket: [SGW-678](https://constellationnetwork.atlassian.net/browse/SGW-678)
NFTs do not update correctly when a user switches between two wallet addresses, leading to an incorrect representation of NFT ownership and an inability to transfer NFTs between the addresses.
[SGW-678]: https://constellationnetwork.atlassian.net/browse/SGW-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 678 nfts section displays wrong nfts when switching wallets

---

source/constants/events.ts
source/navigation/stacks/tabs/Tabs.native.tsx
source/navigation/stacks/tabs/styles.ts
source/scenes/home/Home/Home.native.tsx
source/scenes/home/Home/Home.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/nfts/Collections/Collections.container.tsx
source/scenes/nfts/NFTSend/NFTSend.container.tsx
source/scenes/nfts/NFTSend/NFTSend.native.tsx
source/scenes/nfts/NFTSend/NFTSend.tsx
source/scenes/nfts/NFTSendConfirm/NFTSendConfirm.container.tsx
source/scenes/settings/CheckPassword/CheckPassword.native.tsx
source/scenes/settings/CheckPassword/styles.ts
source/scenes/settings/ManageWallet/ManageWallet.native.tsx
source/scenes/settings/ManageWallet/styles.ts
source/scenes/settings/RemoveWallet/RemoveWallet.native.tsx
source/scenes/settings/RemoveWallet/styles.ts
source/utils/EventEmitter.ts

Ticket: [SGW-679](https://constellationnetwork.atlassian.net/browse/SGW-679)
Users are experiencing difficulties in renaming their wallets in Stargazer particularly noted on an iPhone 8 with iOS 16.2.
[SGW-679]: https://constellationnetwork.atlassian.net/browse/SGW-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 679 fixes issue renaming wallets on mobile

---

source/scenes/home/Asset/Asset/Asset.container.tsx
source/scenes/home/Asset/TxItem/TxItem.container.tsx
source/scenes/home/Asset/TxItem/TxItem.native.tsx
source/scenes/home/Asset/TxItem/TxItem.tsx
source/scenes/home/Asset/TxItem/types.ts
source/scenes/home/Asset/TxsPanel/TxsPanel.container.tsx
source/scenes/home/SendAsset/Send/Send.native.tsx
source/scenes/home/SendAsset/Send/Send.tsx
source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/migration/v4_0_2.ts
source/scripts/Background/migration/v4_0_3.ts
source/state/assets/index.ts
source/state/erc20assets/index.ts
source/state/vault/index.ts

Ticket: [SGW-681](https://constellationnetwork.atlassian.net/browse/SGW-681)
Now that the DOR token is listed on CoinGecko we can fetch the fiat price from the CoinGecko API using the `priceId` they provide.
[SGW-681]: https://constellationnetwork.atlassian.net/browse/SGW-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Juan SGW 681 adds CoinGecko price id to the DOR token

---

source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/migration/v4_0_1.ts
source/scripts/Background/migration/v4_1_0.ts
source/state/assets/index.ts
source/state/erc20assets/index.ts
source/state/vault/index.ts

Ticket: [SGW-691](https://constellationnetwork.atlassian.net/browse/SGW-691)
We need to run a migration process to update LB endpoints in user's local storage.
[SGW-691]: https://constellationnetwork.atlassian.net/browse/SGW-691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-691] update DOR LB endpoints

---

source/scenes/home/Asset/LoadingTxItem/LoadingTxItem.native.tsx
source/scenes/home/Asset/LoadingTxItem/LoadingTxItem.scss
source/scenes/home/Asset/LoadingTxItem/LoadingTxItem.tsx
source/scenes/home/Asset/LoadingTxItem/index.ts
source/scenes/home/Asset/LoadingTxItem/styles.ts
source/scenes/home/Asset/TxItem/TxItem.native.tsx
source/scenes/home/Asset/TxItem/TxItem.scss
source/scenes/home/Asset/TxItem/TxItem.tsx
source/scenes/home/Asset/TxsPanel/TxsPanel.container.tsx
source/scenes/home/Asset/TxsPanel/TxsPanel.native.tsx
source/scenes/home/Asset/TxsPanel/TxsPanel.tsx
source/scenes/home/Asset/TxsPanel/types.ts
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/EthTransactionController.ts
source/state/vault/index.ts
source/state/vault/types.ts

This PR fixes multiple UI/UX bugs:
[LE-810](https://constellationnetwork.atlassian.net/browse/LE-810)
[SGW-703](https://constellationnetwork.atlassian.net/browse/SGW-703)
[SGW-704](https://constellationnetwork.atlassian.net/browse/SGW-704)
[SGW-706](https://constellationnetwork.atlassian.net/browse/SGW-706)
[SGW-707](https://constellationnetwork.atlassian.net/browse/SGW-707)
[LE-810]: https://constellationnetwork.atlassian.net/browse/LE-810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SGW-703]: https://constellationnetwork.atlassian.net/browse/SGW-703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SGW-704]: https://constellationnetwork.atlassian.net/browse/SGW-704?atlOrigin=eyJpIjoiNWRkNTljNzYxN …

bugfix [SGW-707] multiple UI/UX fixes

---

source/native/ios/PrivacyInfo.xcprivacy
source/native/ios/Stargazer.xcodeproj/project.pbxproj

Ticket: [SGW-711](https://constellationnetwork.atlassian.net/browse/SGW-711)
[SGW-711]: https://constellationnetwork.atlassian.net/browse/SGW-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-711] add iOS privacy info file

---

source/components/Menu/Menu.native.tsx
source/components/Menu/Menu.scss
source/components/Menu/Menu.tsx
source/components/Menu/styles.ts
source/components/Menu/types.ts
source/components/ToastAlert/ToastAlert.tsx
source/constants/index.ts
source/scenes/common/Import/ImportPhrase/constants.ts
source/scenes/home/Asset/AssetButtons/AssetButtons.container.tsx
source/scenes/home/BuyAsset/BuyAsset.container.tsx
source/scenes/home/BuyAsset/BuyAsset.native.tsx
source/scenes/home/BuyAsset/BuyAsset.scss
source/scenes/home/BuyAsset/BuyAsset.tsx
source/scenes/home/BuyAsset/styles.ts
source/scenes/home/BuyAsset/types.ts
source/scenes/home/BuyList/BuyList.container.tsx
source/scenes/home/Home/Home.container.tsx
source/scenes/home/Home/Home.native.tsx
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scripts/Background/controllers/AssetsController.ts
source/state/providers/api.ts
source/state/providers/index.ts
source/state/providers/types.ts

Ticket: [SGW-732](https://constellationnetwork.atlassian.net/browse/SGW-732)
- Adds C14 provider as an option to buy assets
[SGW-732]: https://constellationnetwork.atlassian.net/browse/SGW-732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-732] C14 integration

---

source/constants/index.ts
source/navigation/stacks/Root.tsx
source/scenes/home/Asset/AssetButtons/AssetButtons.container.tsx
source/scenes/home/Asset/AssetList/AssetList.container.tsx
source/scenes/home/BuyAsset/BuyAsset.container.tsx
source/scenes/home/BuyList/BuyList.container.tsx
source/scenes/home/BuyList/BuyList.native.tsx
source/scenes/home/BuyList/BuyList.tsx
source/scenes/home/BuyList/types.ts
source/scenes/home/Home/Home.container.tsx
source/scripts/Background/controllers/AssetsController.ts
source/scripts/Background/controllers/ControllerUtils.ts
source/scripts/Background/controllers/EVMChainController/AccountTracker.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/state/assets/index.ts
source/state/providers/api.ts
source/state/providers/index.ts
source/state/providers/types.ts
source/state/vault/index.ts
source/utils/wallet.ts

Ticket: [SGW-730](https://constellationnetwork.atlassian.net/browse/SGW-730)
Adds support for the default tokens list endpoint added in the Lattice API.
[SGW-730]: https://constellationnetwork.atlassian.net/browse/SGW-730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-730] default tokens list

---

source/components/ButtonV3/ButtonV3.tsx
source/components/Card/styles.ts
source/components/CardClaim/CardClaim.native.tsx
source/components/CardClaim/CardClaim.scss
source/components/CardClaim/CardClaim.tsx
source/components/CardClaim/constants.ts
source/components/CardClaim/index.ts
source/components/CardClaim/styles.ts
source/components/CardClaim/types.ts
source/constants/index.ts
source/scenes/home/Home/AssetsPanel/AssetsPanel.container.tsx
source/scenes/home/Home/AssetsPanel/AssetsPanel.native.tsx
source/scenes/home/Home/AssetsPanel/AssetsPanel.tsx
source/scenes/home/Home/AssetsPanel/types.ts
source/scripts/Background/controllers/AssetsController.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/state/rehydrate/index.ts
source/state/store.ts
source/state/user/api.ts
source/state/user/index.ts
source/state/user/types.ts
source/utils/envUtil.native.ts
source/utils/envUtil.ts

Ticket: [SGW-720](https://constellationnetwork.atlassian.net/browse/SGW-720)
Adds Elpaca claim card
[SGW-720]: https://constellationnetwork.atlassian.net/browse/SGW-720?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-720] el paca daily claim

---

source/components/CardClaim/CardClaim.native.tsx
source/components/CardClaim/styles.ts
source/scenes/home/Asset/AssetButtons/AssetButtons.native.tsx
source/scenes/home/Home/Home.native.tsx
source/scenes/home/Home/styles.ts

This PR includes:
- Removes buy feature from iOS
- Updates UI styles for a small issue on Android.

bugfix [SGW 768] remove buy feature from iOS

---

source/native/ReactotronConfig.js
source/native/index.js
source/native/package.json
yarn.lock

- Adds Reactotron library for React Native

feature [SGW] add reactotron

---

source/web/manifest.json

Reference: [SGW-782](https://constellationnetwork.atlassian.net/browse/SGW-782)
- Adds `unlimitedStorage` permission on Chrome to avoid state migration issues
[SGW-782]: https://constellationnetwork.atlassian.net/browse/SGW-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-782] adds unlimited storage permission on chrome

---

source/scenes/home/SendAsset/Confirm/Confirm.native.tsx
source/scenes/home/SendAsset/Confirm/Confirm.tsx

Reference: [SGW-784](https://constellationnetwork.atlassian.net/browse/SGW-784)
- Removes Big Number conversion for USD values
[SGW-784]: https://constellationnetwork.atlassian.net/browse/SGW-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-784] fix NaN amount/fee on the confirm screen

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx

Reference: [SGW-783](https://constellationnetwork.atlassian.net/browse/SGW-783)
- Adds `location.href` validation to handle undefined value on mobile
[SGW-783]: https://constellationnetwork.atlassian.net/browse/SGW-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-783] adds location.href validation

---

source/navigation/stacks/home/Home.tsx
source/scenes/settings/Main/Main.tsx
source/scripts/Background/controllers/WalletController.ts

Ticket: [SGW-780](https://constellationnetwork.atlassian.net/browse/SGW-780)
- Removes unnecessary active wallet reset on logout
[SGW-780]: https://constellationnetwork.atlassian.net/browse/SGW-780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-780] wallet lock reverts active wallet

---

source/components/AssetItem/AssetItem.container.tsx
source/components/AssetItem/AssetItem.native.tsx
source/components/AssetItem/AssetItem.tsx
source/components/AssetItem/types.ts
source/components/LoadingDots/LoadingDots.native.tsx
source/components/LoadingDots/LoadingDots.scss
source/components/LoadingDots/LoadingDots.tsx
source/components/LoadingDots/index.tsx
source/components/LoadingDots/styles.ts
source/components/LoadingDots/types.ts
source/scenes/home/Home/Home.container.tsx
source/scenes/home/Home/Home.native.tsx
source/scenes/home/Home/Home.tsx
source/scenes/home/Home/types.tsx
source/scripts/Background/controllers/EVMChainController/AccountTracker.ts
source/scripts/Background/controllers/EthTransactionController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/state/vault/index.ts
source/state/vault/types.ts

Ticket: [SGW-786](https://constellationnetwork.atlassian.net/browse/SGW-786)
- Adds three dots animation on balance loading
[SGW-786]: https://constellationnetwork.atlassian.net/browse/SGW-786?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-786] balance loading animation

---

source/components/AssetItem/AssetItem.container.tsx
source/components/AssetItem/AssetItem.native.tsx
source/components/AssetItem/AssetItem.tsx
source/components/AssetItem/types.ts
source/scenes/home/Home/Home.container.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/EVMChainController/AccountTracker.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/selectors/flagsSelectors.ts
source/selectors/priceSelectors.ts
source/selectors/vaultSelectors.ts
source/state/flags/index.ts
source/state/flags/types.ts
source/state/store.ts
source/state/vault/index.ts
source/state/vault/types.ts
source/utils/wallet.ts

Ticket: [SGW-789](https://constellationnetwork.atlassian.net/browse/SGW-789)
- Updated assetsBalanceMonitor file to improve the balance loading time making parallel requests
[SGW-789]: https://constellationnetwork.atlassian.net/browse/SGW-789?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-789] improve balance loading time

---

source/scenes/swap/SwapHistory/SwapHistory.scss
source/scenes/swap/TransactionDetails/TransactionDetails.native.tsx
source/scenes/swap/TransactionDetails/TransactionDetails.tsx
source/state/swap/index.ts

[SGW-794](https://constellationnetwork.atlassian.net/browse/SGW-794)
- Fixed store rehydratation issue
- Added optional chaining operator
[SGW-794]: https://constellationnetwork.atlassian.net/browse/SGW-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-794] out of memory after swap

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Confirm/Confirm.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scenes/home/SendAsset/Send/Send.tsx
source/scenes/home/SendAsset/Send/types.ts
source/scripts/Provider/evm/methods/eth_sendTransaction.ts

[SGW-799](https://constellationnetwork.atlassian.net/browse/SGW-799)
- Updates `eth_sendTransaction` to fix amount value in ERC20 transfers
- Updates Send & Confirm screens
[SGW-799]: https://constellationnetwork.atlassian.net/browse/SGW-799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-799] amount not displayed properly on ERC20 transfers

---

source/scenes/home/Home/WalletsModal/WalletsModal.native.tsx
source/scenes/home/Home/WalletsModal/WalletsModal.tsx
source/scenes/home/helpers.tsx
source/scripts/common/eipChainProvider.ts
source/web/pages/Bitfi/Bitfi.tsx

[SGW-801](https://constellationnetwork.atlassian.net/browse/SGW-801)
- Fixes undefined error on Wallets modal
[SGW-801]: https://constellationnetwork.atlassian.net/browse/SGW-801?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-801] wallets modal undefined value

---

source/scenes/swap/SwapTokens/SwapTokens.container.tsx

[SGW-802](https://constellationnetwork.atlassian.net/browse/SGW-802)
- Adds validation for refund/deposit addresses
[SGW-802]: https://constellationnetwork.atlassian.net/browse/SGW-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-802] undefined refund/deposit address

---

source/components/Modal/Modal.native.tsx
source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Confirm/Confirm.native.tsx
source/scenes/home/SendAsset/Confirm/Confirm.scss
source/scenes/home/SendAsset/Confirm/Confirm.tsx
source/scenes/home/SendAsset/Confirm/styles.ts
source/scenes/home/SendAsset/Confirm/types.ts

[SGW-803](https://constellationnetwork.atlassian.net/browse/SGW-803)
- Adds a modal for feeless transaction limit error message
[SGW-803]: https://constellationnetwork.atlassian.net/browse/SGW-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-803] modal for feeless transaction limit error 

---

source/navigation/stacks/home/Home.tsx

[SGW-781](https://constellationnetwork.atlassian.net/browse/SGW-781)
- Update the expiration time if session didn't expired
[SGW-781]: https://constellationnetwork.atlassian.net/browse/SGW-781?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-781] Increase time between wallet lock outs

---

source/scenes/home/SendAsset/Confirm/Confirm.container.tsx
source/scenes/home/SendAsset/Send/Send.container.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/types.ts

[SGW-812](https://constellationnetwork.atlassian.net/browse/SGW-812)
- Fixes amount value for ERC-20 transfers
[SGW-812]: https://constellationnetwork.atlassian.net/browse/SGW-812?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-812] gas fee error on ERC-20 transfers

---

source/scripts/Background/helpers/assetsBalanceMonitor.ts

[SGW-816](https://constellationnetwork.atlassian.net/browse/SGW-816)
- Metagraph token balances are now using L0 api instad of BE
[SGW-816]: https://constellationnetwork.atlassian.net/browse/SGW-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature [SGW-816] fetch metagraph token balances directly from L0

---

source/web/pages/Bitfi/Bitfi.tsx

[SGW-817](https://constellationnetwork.atlassian.net/browse/SGW-817)
- Decode Stargazer message only on signing flows
[SGW-817]: https://constellationnetwork.atlassian.net/browse/SGW-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-817] unable to import Bitfi

---

source/dag4/block-explorer.ts
source/dag4/metagraph.ts
source/native/metro.config.js
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/scripts/Provider/constellation/methods/dag_allowSpend.ts
source/scripts/Provider/constellation/methods/dag_tokenLock.ts
source/web/webpack.config.js
tsconfig.json

[SGW-831](https://constellationnetwork.atlassian.net/browse/SGW-831)
- Fetch balances directly from BE api instead of local state 
[SGW-831]: https://constellationnetwork.atlassian.net/browse/SGW-831?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-831] fetch balance from be api

---

source/web/pages/Bitfi/Bitfi.tsx

[SGW-835](https://constellationnetwork.atlassian.net/browse/SGW-835)
- Removed unnecessary message decoding on the sign transaction flow
[SGW-835]: https://constellationnetwork.atlassian.net/browse/SGW-835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-835] bitfi sign transaction

---

source/components/CardClaim/CardClaim.container.tsx
source/scripts/Background/controllers/AssetsController.ts
source/selectors/userSelectors.ts
source/state/user/api.ts
source/state/user/index.ts
source/utils/sentry.native.ts
source/utils/sentry.ts
source/web/sentry/initialize.ts

[SGW-850](https://constellationnetwork.atlassian.net/browse/SGW-850)
- Show error message if claim request fails
- Improve errors on Sentry for debugging
[SGW-850]: https://constellationnetwork.atlassian.net/browse/SGW-850?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-850] improve error handling on paca claim

---

source/scenes/external/AllowSpend/index.tsx
source/scenes/external/TokenLock/index.tsx
source/scripts/Provider/constellation/methods/dag_allowSpend.ts
source/scripts/Provider/constellation/methods/dag_tokenLock.ts

[SGW-856](https://constellationnetwork.atlassian.net/browse/SGW-856)
- Remove balance check on token lock & allow spend
- Improve message for insufficient balance error
[SGW-856]: https://constellationnetwork.atlassian.net/browse/SGW-856?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

bugfix [SGW-856] remove balance check

---

source/scripts/Background/controllers/MigrationController.ts
source/scripts/Background/migration/v5_3_5.ts
source/state/erc20assets/index.ts
source/state/vault/index.ts

[SGW-861](https://constellationnetwork.atlassian.net/browse/SGW-861)
- Add `priceId` on UP token
- Update nodes (l0/l1 endpoints) on NDT token
[SGW-861]: https://constellationnetwork.atlassian.net/browse/SGW-861?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat [SGW-861] update UP and NDT tokens

---

source/scenes/external/Layouts/CardLayout/index.module.scss
source/scenes/external/Layouts/CardLayout/index.tsx
source/scenes/external/WatchAsset/index.tsx
source/scripts/Background/controllers/AccountController.ts
source/scripts/Background/controllers/AssetsController.ts
source/scripts/Background/controllers/WalletController.ts
source/scripts/Background/handlers/handleStoreSubscribe.ts
source/scripts/Background/helpers/assetsBalanceMonitor.ts
source/scripts/InjectedScript/is_message_broker.ts
source/scripts/Provider/constellation/methods/dag_getMetagraphBalance.ts
source/scripts/Provider/constellation/utils/index.ts
source/state/vault/index.ts
source/utils/objects.ts

[SGW-886](https://constellationnetwork.atlassian.net/browse/SGW-886)
- `wallet_watchAsset` ensures that the token is added in localStorage
- `dag_getMetagraphBalance` fetches balance directly from the metagraph
- Add custom assets (ERC-20 and L0) now works like upsert.
[SGW-886]: https://constellationnetwork.atlassian.net/browse/SGW-886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

hotfix [SGW-886] fix wallet watch asset
